services:
  postgresdb:
    image: postgres:15
    restart: unless-stopped
    container_name: matchaForms-pg

    environment:
      POSTGRES_USER: zeal
      POSTGRES_PASSWORD: postgreszeal2108
      POSTGRES_DB: matchaForms-dev

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
